// Code generated by mockit.
// DO NOT EDIT!

package mocks

import "github.com/hamster2020/gauth"

type mockDatastore struct {
	CreateUserFunc  func(u gauth.User) error
	UserByEmailFunc func(email string) (gauth.User, error)
	UpdateUserFunc  func(email string, u gauth.User) error
	DeleteUserFunc  func(email string) error
	UsersFunc       func() ([]gauth.User, error)
}

func NewMockDatastore() *mockDatastore {
	return &mockDatastore{}
}

func (ds *mockDatastore) CreateUser(u gauth.User) error {
	return ds.CreateUserFunc(u)
}

func (ds *mockDatastore) UserByEmail(email string) (gauth.User, error) {
	return ds.UserByEmailFunc(email)
}

func (ds *mockDatastore) UpdateUser(email string, u gauth.User) error {
	return ds.UpdateUserFunc(email, u)
}

func (ds *mockDatastore) DeleteUser(email string) error {
	return ds.DeleteUserFunc(email)
}

func (ds *mockDatastore) Users() ([]gauth.User, error) {
	return ds.UsersFunc()
}
