// Code generated by mockit.
// DO NOT EDIT!

package mocks

import "github.com/hamster2020/gauth"

type MockLogic struct {
	AuthenticateFunc func(c gauth.Credentials) (string, error)
	CreateUserFunc   func(req gauth.UserRequest) error
	UserByEmailFunc  func(email string) (gauth.User, error)
	UpdateUserFunc   func(oldEmail string, req gauth.UserRequest) error
	DeleteUserFunc   func(email string) error
	UsersFunc        func() ([]gauth.User, error)
}

func NewMockLogic() *MockLogic {
	return &MockLogic{}
}

func (logic *MockLogic) Authenticate(c gauth.Credentials) (string, error) {
	return logic.AuthenticateFunc(c)
}

func (logic *MockLogic) CreateUser(req gauth.UserRequest) error {
	return logic.CreateUserFunc(req)
}

func (logic *MockLogic) UserByEmail(email string) (gauth.User, error) {
	return logic.UserByEmailFunc(email)
}

func (logic *MockLogic) UpdateUser(oldEmail string, req gauth.UserRequest) error {
	return logic.UpdateUserFunc(oldEmail, req)
}

func (logic *MockLogic) DeleteUser(email string) error {
	return logic.DeleteUserFunc(email)
}

func (logic *MockLogic) Users() ([]gauth.User, error) {
	return logic.UsersFunc()
}
